In [2]:
import pandas as pd
import numpy as np

In [3]:
sub = pd.read_csv("sub.csv")

In [4]:
sub.head(50)

    PassengerId  Survived
0           892         0
1           893         0
2           894         0
3           895         1
4           896         0
5           897         0
6           898         0
7           899         0
8           900         0
9           901         0
10          902         1
11          903         0
12          904         1
13          905         0
14          906         1
15          907         1
16          908         0
17          909         0
18          910         0
19          911         0
20          912         0
21          913         1
22          914         1
23          915         1
24          916         1
25          917         0
26          918         1
27          919         0
28          920         0
29          921         0
30          922         0
31          923         0
32          924         1
33          925         0
34          926         0
35          927         0
36          928         0
37          929         1
38          930         0
39          931         1
40          932         0
41          933         0
42          934         0
43          935         1
44          936         1
45          937         0
46          938         0
47          939         0
48          940         1
49          941         0